import{i as u,S as g}from"./assets/vendor-Dg3uDB0e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();const e={key:"29531534-c6f4c4079f81828b6fd250707",URL:"https://pixabay.com/api/",image_type:"photo",orientation:"horizontal",per_page:20,page:1,checkCountOfPhotos:0,galleryList:document.querySelector(".gallery__list"),searchButton:document.querySelector('button[type="submit"]'),searchInput:document.querySelector("input"),loadMoreButton:document.querySelector(".load-more"),infoLoadingMessage:document.querySelector(".info--container")},d=async i=>{try{const o=await fetch(i);if(!o.ok)throw new Error(`HTTP error! Status: ${o.status}`);const n=await o.json();if(console.dir(n),n.totalHits===0)return u.warning({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again."}),e.loadMoreButton.style.display="none","";u.success({title:"Success!",message:`Hooray! We found ${n.totalHits} images.`});const s=r=>{const l=Number(r);return isNaN(l)?r:l>=1e6?(l/1e6).toFixed(1).replace(/\.0$/,"")+"M":l>=1e3?(l/1e3).toFixed(1).replace(/\.0$/,"")+"K":l.toString()},t=n.hits.map(r=>`
        <li class="gallery__item">
          <div class="img--wrap">
            <a class="gallery__link" href="${r.largeImageURL}" target="_parent" rel="noopener noreferrer">
              <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            </a>
          </div>
          <div class="gallery__item--info">
            <ul class="gallery__item--style"><li>Likes</li><li>${s(r.likes)}</li></ul>
            <ul class="gallery__item--style"><li>Views</li><li>${s(r.views)}</li></ul>
            <ul class="gallery__item--style"><li>Comments</li><li>${s(r.comments)}</li></ul>
            <ul class="gallery__item--style"><li>Downloads</li><li>${s(r.downloads)}</li></ul>
          </div>
        </li>`).join(""),a=Math.ceil(n.totalHits/e.per_page);return e.page>=a?(u.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),e.loadMoreButton.style.display="none"):e.loadMoreButton.style.display="flex",t}catch(o){return console.error(o),u.error({title:"Error",message:"Something went wrong while fetching images."}),e.loadMoreButton.style.display="none",""}};let c=null;async function p(i){i.preventDefault();const o=e.searchInput.value.trim();if(!o)return;e.infoLoadingMessage.innerHTML="Loading images, please wait...",e.page=1,e.galleryList.innerHTML="",window.scrollTo({top:0,behavior:"smooth"});const n=`${e.URL}?key=${e.key}&q=${encodeURIComponent(o)}&image_type=${e.image_type}&orientation=${e.orientation}&per_page=${e.per_page}&page=${e.page}`,s=await d(n);e.infoLoadingMessage.innerHTML="",e.galleryList.insertAdjacentHTML("beforeend",s),c?c.refresh():c=new g(".gallery__link",{captionsData:"alt",captionDelay:250})}async function y(i){i.preventDefault(),e.infoLoadingMessage.innerHTML="Loading images, please wait...",e.searchButton.disabled=!0,e.searchButton.style.backgroundColor="#808080",e.page+=1;const o=e.searchInput.value.trim(),n=`${e.URL}?key=${e.key}&q=${encodeURIComponent(o)}&image_type=${e.image_type}&orientation=${e.orientation}&per_page=${e.per_page}&page=${e.page}`,s=await d(n),t=e.galleryList.scrollHeight;e.infoLoadingMessage.innerHTML="",e.galleryList.insertAdjacentHTML("beforeend",s),c==null||c.refresh(),window.scrollTo({top:t-100,behavior:"smooth"}),e.searchButton.disabled=!1,e.searchButton.style.backgroundColor="#4e75ff"}console.log("start");console.log(e);e.searchButton.addEventListener("click",p);e.loadMoreButton.addEventListener("click",y);
//# sourceMappingURL=index.js.map
