import{i as u,S as g}from"./assets/vendor-Dg3uDB0e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const e={key:"29531534-c6f4c4079f81828b6fd250707",URL:"https://pixabay.com/api/",image_type:"photo",orientation:"horizontal",per_page:20,page:1,checkCountOfPhotos:0,galleryList:document.querySelector(".gallery"),searchButton:document.querySelector('button[type="submit"]'),searchInput:document.querySelector("input"),loadMoreButton:document.querySelector(".load-more"),infoLoadingMessage:document.querySelector(".info--container")},d=async i=>{try{const r=await fetch(i);if(!r.ok)throw new Error(`HTTP error! Status: ${r.status}`);const s=await r.json();if(s.totalHits===0)return u.warning({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again."}),e.loadMoreButton.style.display="none","";u.success({title:"Success!",message:`Hooray! We found ${s.totalHits} images.`});const n=o=>{const l=Number(o);return isNaN(l)?o:l>=1e6?(l/1e6).toFixed(1).replace(/\.0$/,"")+"M":l>=1e3?(l/1e3).toFixed(1).replace(/\.0$/,"")+"K":l.toString()},t=s.hits.map(o=>`
        <li class="gallery__item">
          <div class="img--wrap">
            <a class="gallery__link" href="${o.largeImageURL}" target="_parent" rel="noopener noreferrer">
              <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
            </a>
          </div>
          <div class="gallery__item--info">
            <ul class="gallery__item--style"><li>Likes</li><li>${n(o.likes)}</li></ul>
            <ul class="gallery__item--style"><li>Views</li><li>${n(o.views)}</li></ul>
            <ul class="gallery__item--style"><li>Comments</li><li>${n(o.comments)}</li></ul>
            <ul class="gallery__item--style"><li>Downloads</li><li>${n(o.downloads)}</li></ul>
          </div>
        </li>`).join(""),a=Math.ceil(s.totalHits/e.per_page);return e.page>=a?(u.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),e.loadMoreButton.style.display="none"):e.loadMoreButton.style.display="flex",t}catch(r){return console.error(r),u.error({title:"Error",message:"Something went wrong while fetching images."}),e.loadMoreButton.style.display="none",""}};let c=null;async function p(i){i.preventDefault();const r=e.searchInput.value.trim();if(!r)return;e.infoLoadingMessage.innerHTML="Loading images, please wait...",e.page=1,e.galleryList.innerHTML="",window.scrollTo({top:0,behavior:"smooth"});const s=`${e.URL}?key=${e.key}&q=${encodeURIComponent(r)}&image_type=${e.image_type}&orientation=${e.orientation}&per_page=${e.per_page}&page=${e.page}`,n=await d(s);e.infoLoadingMessage.innerHTML="",e.galleryList.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new g(".gallery__link",{captionsData:"alt",captionDelay:250})}async function y(i){i.preventDefault(),e.infoLoadingMessage.innerHTML="Loading images, please wait...",e.searchButton.disabled=!0,e.searchButton.style.backgroundColor="#808080",e.page+=1;const r=e.searchInput.value.trim(),s=`${e.URL}?key=${e.key}&q=${encodeURIComponent(r)}&image_type=${e.image_type}&orientation=${e.orientation}&per_page=${e.per_page}&page=${e.page}`,n=await d(s),t=e.galleryList.scrollHeight;e.infoLoadingMessage.innerHTML="",e.galleryList.insertAdjacentHTML("beforeend",n),c==null||c.refresh(),window.scrollTo({top:t-100,behavior:"smooth"}),e.searchButton.disabled=!1,e.searchButton.style.backgroundColor="#4e75ff"}e.searchButton.addEventListener("click",p);e.loadMoreButton.addEventListener("click",y);
//# sourceMappingURL=index.js.map
